# YAML config to be placed in root of docker base image
# projects.

name: build_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: templates
      type: github
      name: illuscio-dev/azure-pipelines-templates
      endpoint: Github_Read

trigger:
  batch: true
  branches:
    include:
      - master
    exclude:
      - build_*

schedules:
# will execute every night at 1:00 am. We do this to keep third-party dependencies up
# to date.
- cron: 0 1 * * *
  displayName: Nightly Build
  branches:
    include:
      - master
  always: true

variables:
  # Link to the variables template.
  - template: variables.yml@templates

jobs:
  # Link to the pipeline template.
  - template: docker_image_main.yml@templates
    parameters:
      pypiAzureArtifactFeed: astral-pypi
      imageName: image-name-goes-here
