parameters:
  # Python Version to Use for build.
  - name: imageName
    type: string

  # Python Version to Use for Build
  - name: pythonVersion
    type: string
    default: 3.8

  # Artifact feed to pull custom packages from
  - name: pypiAzureArtifactFeed
    type: string

jobs:

- job: 'Build_Publish'
  timeoutInMinutes: 5
  cancelTimeoutInMinutes: 2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - template: python_setup.yml
    parameters:
      pypiAzureArtifactFeed: ${{parameters.pypiAzureArtifactFeed}}
      installLocalPackage: false

  - script: docker -v
    displayName: Printing docker version info

  - script: docker login $REGISTRY_URL -u $DOCKER_ID -p $DOCKER_PASSWORD
    displayName: "Logging into DockerHub"
    env:
      DOCKER_ID: $(CONTAINER_REGISTRY_ID)
      DOCKER_PASSWORD: $(CONTAINER_REGISTRY_PASSWORD)
      REGISTRY_URL: $(CONTAINER_REGISTRY_URL)

  - script: |
      docker build \
      --no-cache \
      --build-arg PIP_INDEX_URL=$PIP_INDEX_URL \
      --build-arg PIP_EXTRA_INDEX_URL=$PIP_EXTRA_INDEX_URL \
      -t $REGISTRY_URL/${{parameters.imageName}}:latest .
    env:
      REGISTRY_URL: $(CONTAINER_REGISTRY_URL)
      PIP_INDEX_URL: $(PIP_INDEX_URL)
      PIP_EXTRA_INDEX_URL: $(PIP_EXTRA_INDEX_URL)
      DOCKER_BUILDKIT: 1
    displayName: 'Building Docker Image'

  - script: docker push $REGISTRY_URL/${{parameters.imageName}}
    displayName: 'Upload Image'
    env:
      REGISTRY_URL: $(CONTAINER_REGISTRY_URL)
